### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by kulbshar**
Hello Sir,

Thanks for the video you have posted on youtube to create Covid19 Dashboard. 
I have tried to make few updates in it. to have two charts (one on the left for confirmed cases & other on the right for death cases). in the middle I kept the mapchart as it is.

Though the mapcharts looks good and give you confirmed cases counts when you hover over it. what I really like to do more 
is having color of country differ based on count of confirmed cases like we had for population density.

For example:
in the below code we have pass dataForMap data2 to change population density count to confirmed cases counts but in the Highcharts.getJSON we are still using p.value (which is population density). I tried few methods to get this data from our data2 dataForMap but was not successfull. I am not at all familiar with JS.

    **var data2 = {{ dataForMap | safe}};**

    // Highcharts.getJSON('/static/firstUI/world-population-density.json', function (data) {
    Highcharts.getJSON('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json', function (data) {
        // Prevent logarithmic errors in color calulcation
        data.forEach(function (p) {
            p.value = (p.value < 1 ? 1 : p.value);
        });

 
Could you please advise me how can I resolve it?

Below is the screenshot my dashboard look like.

screenshot_covid_dash

Thank you!!
Regards,

### CODE REVIEW

**Comment by sharmasw** [comment]
Hi:

Great you are practicing with the code, Just one thing, if you looked into the example code which I followed https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/tooltip/
has a color intensity changing like a heat map. if you can check what's missing in the code from the sample and in the codebase.
I could not immediately check the code and confirm what's missing.

**Comment by kulbshar** [comment]
Thanks. after comparing sample map (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/tooltip/) with my code base I see the different is when I change data in series to data2.
below is the code:
           series: [{
                data: data2,
                joinBy: ['iso-a3', 'code3'],
                name: 'Population density',
                states: {
                    hover: {
                        color: '#a4edba'
                    }
                }
            }]

The original data=data keep color in the map according to population density (higher the density darker the color).
I think the problem is 
data from json  file(world-population-density.json) still using use population in column value. while we are data2(var data2 = {{ dataForMap | safe}};) in series which is coming from view.
  
    Highcharts.getJSON('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json', function (data) {

        // Prevent logarithmic errors in color calulcation
        data.forEach(function (p) {
            p.value = (p.value < 1 ? 1 : p.value);
        });


I didn't see any other difference.

Note:  I used the JS from https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/tooltip/ & change "container" to mapchart (same as in id in html page) & change data to dat2 which coming from view (var data2 = {{ dataForMap | safe}};)

Thanks.

**Comment by kulbshar** [comment]
> Hi:
> 
> Great you are practicing with the code, Just one thing, if you looked into the example code which I followed https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/tooltip/
> has a color intensity changing like a heat map. if you can check what's missing in the code from the sample and in the codebase.
> I could not immediately check the code and confirm what's missing.

**Comment by kulbshar** [comment]
I got it now. Sorry I was confused with highchart. resolved it after changing colorAxis range. Thank you!!

**Pull request closed without merging**
